# Seed Data

Player.create!(first_name: 'Sabrish', last_name: 'Kumar', email: 'skumar@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','sabarish.jpg')))
Player.create!(first_name: 'Sukeerthi', last_name: 'Adiga', email: 'sadiga@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','adiga.jpg')))
Player.create!(first_name: 'Nitin', last_name: 'Misra', email: 'nitinmisra@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','nitin.jpg')))
Player.create!(first_name: 'Satish', last_name: 'Purushottam', email: 'psatish@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','sathesh.jpg')))
Player.create!(first_name: 'Sasindaran', last_name: 'Indrajit', email: 'sasip@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','sasi.jpg')))
Player.create!(first_name: 'Ranjit', last_name: 'Loganathan', email: 'lranjit@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','ranjith.jpg')))
Player.create!(first_name: 'Ravi', last_name: 'Kiran', email: 'ravikiran@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','ravi.jpg')))
Player.create!(first_name: 'Malai', last_name: 'Swami', email: 'smalai@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','malai.jpg')))
Player.create!(first_name: 'Rajiv', last_name: 'Ratan', email: 'rajivratan@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','rajiv.jpg')))
Player.create!(first_name: 'Dilip', last_name: 'Libramani', email: 'ldilip@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','dilip.jpg')))
Player.create!(first_name: 'Debasis', last_name: 'Bora', email: 'debasis@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','debasis.jpg')))
Player.create!(first_name: 'Praveen', last_name: 'Kumar', email: 'praveen@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','praveen.jpg')))
Player.create!(first_name: 'Venu', last_name: 'Gopal', email: 'venu@crri.co.in', avatar: File.open(File.join(Rails.root, 'public', 'avatars','venu.jpg')))
